### ISSUE TITLE
Characters detection

### ISSUE THREAD

**Issue by frayalisia** [frayalisia/novelgraphs#8]
- доделать словарь героев
- научиться выделять именованных героев из текста
- понимать, от какого лица то или иное произведение

**Comment by PavelNovichkov** [comment]
Subissues:
- [x] #11 Test `Character` annotator
- [x] #14 Implement `FirstPerson` annotator
- [x] #15 Add narrator to characters
